import { Fragment } from "react";
import Head from "next/head";
import UserWrapper from "./UserWrapper";
import { userData } from "../utils/authentication";

const Layout = ({ children }) => {
  return (
    <Fragment>
      <Head>
        <title>Authentication</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="header">
        <span>Authentication</span>
      </header>
      <UserWrapper user={userData()} />
      <main className="main">{children}</main>
    </Fragment>
  );
};

export default Layout;
